version: 0.1.0

project: demo-ros1-turtlesim-forked # change to match your project name in the dashboard
jobs:
  basic_turtle: # Overall job name
    type: test
    runtime:
      simulator: turtlesim
      framework: ros1:0
    timeout: 5 # minutes
    scenarios:
      defaults: # Global to all scenarios, and overriden in specific scenarios.
        output_path: /tmp/outputs/
        reuse-master: False  # if True: rostest will use the host's rosmaster instead of spining up an isolated rostest network
        subscriptions:
          pose: turtle1/pose
          result: turtle1/odometry
        rosbag-record: subscriptions
        ros_testpackage: turtle_odometry
        ros_testfile: turtle_odometry.launch
        rosbag-postprocess: turtle_post_process.py
      settings:
        # - name: turtle
        #   params:
        #     # test/param1: 1
        #     # test/nested_ns/param2: 2.5
        #     test/start_pose: [[1, 1, 0]]  # [x, y, theta]
        #     test/segment_length: 5  # for square trajectory
        #     test/odom_tuning_theta: 0.01   # demo: tune odometry algorithm
        #     test/odom_tuning_forward: 0.1  # demo: tune odometry algorithm
        - name: turtle_quick
          params:
            test/start_pose: [[1, 1, 0]]  # [x, y, theta]
            test/segment_length: 1  # for square trajectory
            test/odom_tuning_theta: 0.01   # demo: tune odometry algorithm
            test/odom_tuning_forward: 0.1  # demo: tune odometry algorithm
        # - name: turtle_fail
        #   params:
        #     test/start_pose: [[-1, 1, 0]]  # [x, y, theta]
        #     test/segment_length: 1  # for square trajectory
        #     test/odom_tuning_theta: 0.01   # demo: tune odometry algorithm
        #     test/odom_tuning_forward: 0.1  # demo: tune odometry algorithm
        # - name: turtle_gridsearch_traj
        #   params:
        #     test/start_pose: [[1, 1, 0], [2.5, 2.5, 0]]  # [x, y, theta]
        #     test/segment_length: [7, 2]  # for square trajectory
        #     test/odom_tuning_theta: 0.01   # demo: tune odometry algorithm
        #     test/odom_tuning_forward: 0.1  # demo: tune odometry algorithm
        # - name: turtle_gridsearch_odom
        #   params:
        #     test/start_pose: [[1, 1, 0]]  # [x, y, theta]
        #     test/segment_length: 7  # for square trajectory
        #     test/odom_tuning_theta: [0, 0.01, 0.1]   # demo: tune odometry algorithm
        #     test/odom_tuning_forward: 0.1  # demo: tune odometry algorithm
