version: 0.1.0

project: demo-ros1-turtlesim-forked # change to match your project name in the dashboard
jobs:
  basic_turtle: # Overall job name
    type: test
    runtime:
      simulator: turtlesim
      framework: ros1:0
    timeout: 5 # minutes
    scenarios:
      defaults: # Global to all scenarios, and overriden in specific scenarios.
        reuse-master: False  # if True: rostest will use the host's rosmaster instead of spining up an isolated rostest network
        subscriptions:
          pose: turtle1/pose
          result: turtle1/odometry
      settings:
        - name: turtle
          ros1_testpackage: turtle_odometry
          ros1_testfile: turtle_odometry.launch
          ros1_postprocess: turtle_post_process.py
          params:
            # test/param1: 1
            # test/param1: [3, 2, 1]
            # test/nested_ns/param2: 2.5
            test/start_pose: [[1, 1, 0]]  # [x, y, theta]
            # test/start_pose: [[1, 1, 0], [2.5, 2.5, 0]]  # [x, y, theta]
            # test/segment_length: [7, 2]  # for square trajectory
            test/segment_length: 5  # for square trajectory
            test/odom_tuning_theta: 0.01   # demo: tune odometry algorithm
            test/odom_tuning_forward: 0.1  # demo: tune odometry algorithm
            # test/odom_tuning_theta: [0, 0.01, 0.1]   # demo: tune odometry algorithm
            # test/odom_tuning_forward: [0, 0.1, 0.5]  # demo: tune odometry algorithm
