FROM ros:noetic-ros-core

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get upgrade -y
RUN apt install -y --no-install-recommends python3-pip 
RUN pip install --upgrade setuptools
RUN pip install artefacts-client --extra-index-url https://d5cw4z7oemmfd.cloudfront.net/pep503/ -U
RUN apt install curl lsb-release git wget gnupg cmake build-essential python3-catkin-tools python3-osrf-pycommon python3-rospy ros-noetic-turtlesim ros-noetic-rosbag -y
RUN pip3 install --upgrade numpy ruamel.yaml matplotlib bqplot pyyaml plotly
RUN pip3 install pandas

COPY . /ws/src

WORKDIR /ws

RUN source /opt/ros/noetic/setup.bash && catkin config --init && catkin build

WORKDIR /ws/src

CMD source /ws/devel/setup.bash --extend && QT_QPA_PLATFORM=offscreen artefacts run $ARTEFACTS_JOB_NAME
